---
- name: Gathering Facts
  when:
    - ansible_os_family is not defined or
      ansible_distribution is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - os_family
      - distribution

- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Include OS variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Install Hashicorp Vault
  become: true
  ansible.builtin.package:
    name:
      - vault
    state: present

- name: Configure firewalld to allow Vault traffic
  when:
    - vault_configure_firewalld
  become: true
  ansible.posix.firewalld:
    port: 8200/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Run Vault server in development mode
  become: true
  ansible.builtin.shell: "/usr/bin/vault server -dev -dev-root-token-id={{ vault_token }} -dev-listen-address=0.0.0.0:{{ vault_listen_port }} > /dev/null 2>&1 &"
  changed_when: true
  tags:
    - always
    - molecule-idempotence-notest

- name: Wait for Vault to start
  delegate_to: localhost
  ansible.builtin.wait_for:
    host: "{{ vault_listen_address }}"
    port: "{{ vault_listen_port }}"
